### ISSUE TITLE
Invalid spi() object in AccelMagno library

### ISSUE THREAD

**Issue by aaron-hurst** [kjph/c7c-atamo-dusty#12]
# Description

The AccelMagno source code uses an object called spi which causes a build error in Atmel Studio 7:
![image](https://user-images.githubusercontent.com/26296815/31583361-ce4932d0-b1cc-11e7-9cb6-ebd62437fc40.png)

# Cause

The original (pre-version 1.0.1 of duinoPRO) dP_AccelMagno.h file included dP_Module.h which seems to have defined the SPI interfact for the module, including declaring spi. spi was decpared as a "dP_Spi" class, which appears to be a wrapper for the standard Arduino SPI library. (See below screenshot taken from dP_Spi.cpp for evidence to support this conclusion)
![image](https://user-images.githubusercontent.com/26296815/31583401-8daa5af0-b1cd-11e7-926a-4698018d58fe.png)

dP_Spi.* has no analogue in the v1.0.1 duinoPRO software. v1.0.1 seems to rely only on the standard Arduino SPI library. Therefore, "spi" is clearly not declared in the scope of the AccelMagno library.

# Action

It is suspected that the commands needed for the AccelMagno library can be re-implemented, using just the Arduino SPI.h library to replace the need for the old dP_Spi class.

See dP_Spi.* in pre-v1.0.1 duinoPRO software for what the original functions were and AccelMagno.cpp in the current mote-sample branch for what was used previously/needs to be replaced. Then re-implement/work around the old spi() functions.

**Comment by ghost** [comment]
Closed with 39d76d6a54f5a9a1bb7a2a1d2ee4d78de83efe42
